swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport : gmail
    host: smtp.gmail.com
    port: 465
    auth_mode: login
    username: swapit.esgi@gmail.com
    password: Password123&
    encryption: ssl
    stream_options:
